name=IS31FL3731
version=1.0.0
author=Lorenzo Petrecca
maintainer=Lorenzo Petrecca <lollo.petrecca1998@gmail.com>
sentence=A versatile library for controlling IS31FL3731 LED matrix displays with easy-to-use functions.
paragraph=This library provides a simple and efficient way to interface with IS31FL3731 LED matrices on Arduino and ESP32 platforms. It includes functions for setting up the matrix, writing frames, and controlling individual LEDs. The library supports the management of up to 4 IS31FL3731 drivers simultaneously, making it suitable for larger LED matrix setups. It is compatible with multiple platforms and requires minimal code to get started.
category=Display
url=https://github.com/lorenzo-petrecca/
architectures=avr,esp32
depends=